---
providers:
  route53:
    class: octodns.provider.route53.Route53Provider
    access_key_id: env/AWS_ACCESS_KEY_ID
    secret_access_key: env/AWS_SECRET_ACCESS_KEY
  tinydns:
    class: octodns.source.tinydns.TinyDnsFileSource
    # The location of the TinyDNS zone files
    directory: ../../dns/bytemark/data/
    default_ttl: 3600

zones:
  jcm-systems.co.uk.: &sync2aws
    sources:
    - tinydns
    targets:
    - route53
  jcm.systems.: *sync2aws
  jpluscplusm.com.: *sync2aws
  jpcpm.net.: *sync2aws
